### ISSUE TITLE
pako uses outdated version of zlib which causes problems with other libs

### ISSUE THREAD

**Issue by LJNeon** [nodeca/pako#143]
For example `sharp`, when I try to use `sharp` and `pako` is required first it gives the following error:
```
Error: /lib/x86_64-linux-gnu/libz.so.1: version `ZLIB_1.2.9' not found (required by /home/ubuntu/workspace/ffa/node_modules/sharp/build/Release/../../vendor/lib/libpng16.so.16)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:718:18)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/home/ubuntu/workspace/ffa/node_modules/sharp/lib/constructor.js:10:15)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
```
I can require `sharp` first to avoid this error but updating the version `pako` uses seems much better.

Furthermore, the zlib 1.2.8 version contains a bug which accepts invalid headers when `windowBits` is zero. This took us a while to figure out, and happens to be [fixed in 1.2.9+](https://zlib.net/ChangeLog.txt).

**Comment by puzrin** [comment]
I'm not sure your sharp's problems are related to pako. Anyway, if someone wish to update sources - PR welcome.

**Comment by puzrin** [comment]
I tend to close this, since description is confusing and seems not related to this package. The only correct statement is "pako needs sync with newer zlib". That's indirectly mentioned in #107, but new issue can be created if that helps to anyone

**Comment by LJNeon** [comment]
Yea I poorly wrote this issue, go ahead and make a new issue for the newer zlib sync.
