### ISSUE TITLE
Cannot install pako

### ISSUE THREAD

**Issue by BaronChen** [nodeca/pako#273]
`npm i pako` returns the following error:
40 http fetch GET 200 https://registry.npmmirror.com/pako 186ms (cache hit)
41 silly placeDep ROOT pako@ OK for:  want: *
42 timing idealTree:#root Completed in 193ms
43 timing idealTree:node_modules/pako Completed in 0ms
44 timing idealTree:buildDeps Completed in 195ms
45 timing idealTree:fixDepFlags Completed in 0ms
46 timing idealTree Completed in 208ms
47 timing command:install Completed in 217ms
48 verbose type range
49 verbose stack pako: No versions available for pako
49 verbose stack     at pickManifest (/Users/baron/.nvm/versions/node/v18.15.0/lib/node_modules/npm/node_modules/npm-pick-manifest/lib/index.js:140:25)
49 verbose stack     at module.exports (/Users/baron/.nvm/versions/node/v18.15.0/lib/node_modules/npm/node_modules/npm-pick-manifest/lib/index.js:187:16)
49 verbose stack     at RegistryFetcher.manifest (/Users/baron/.nvm/versions/node/v18.15.0/lib/node_modules/npm/node_modules/pacote/lib/registry.js:119:22)
49 verbose stack     at async [nodeFromEdge] (/Users/baron/.nvm/versions/node/v18.15.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1059:19)
49 verbose stack     at async [buildDepStep] (/Users/baron/.nvm/versions/node/v18.15.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:929:11)
49 verbose stack     at async Arborist.buildIdealTree (/Users/baron/.nvm/versions/node/v18.15.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:207:7)
49 verbose stack     at async Arborist.reify (/Users/baron/.nvm/versions/node/v18.15.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:159:5)
49 verbose stack     at async Install.exec (/Users/baron/.nvm/versions/node/v18.15.0/lib/node_modules/npm/lib/commands/install.js:146:5)
49 verbose stack     at async module.exports (/Users/baron/.nvm/versions/node/v18.15.0/lib/node_modules/npm/lib/cli.js:134:5)

**Comment by kflorence** [comment]
I just installed it without issue.
